spring.application.name=user
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/user-service
spring.datasource.username=postgres
spring.datasource.password=jurubebapostgres
spring.jpa.show-sql=true
server.port=8081

spring.jpa.properties.hibernate.hbm2ddl.auto=validate
